def isSpringBoot4 = VersionNumber.parse("${springBootVersion}").getMajor() >= 4

sourceSets {
    main {
        java {
            srcDir isSpringBoot4 ? 'src/main/java4' : 'src/main/java3'
        }
    }
}

dependencies {
    implementation project(':demo-shared')
    implementation project(':demo-api')
    implementation project(':demo-security')
    implementation project(':sbp-core')

    implementation project(':sbp-spring-boot-thymeleaf-starter')
}

//*************************************************************************
// App Properties
//*************************************************************************

mainClassName = 'demo.sbp.admin.AdminPluginStarter'

manifest {
    attributes 'Main-Class': 'demo.sbp.admin.AdminPluginStarter'
}