def isSpringBoot4 = VersionNumber.parse("${springBootVersion}").getMajor() >= 4

sourceSets {
    test {
        java {
            srcDir isSpringBoot4 ? 'src/test/java4' : 'src/test/java3'
        }
    }
}

dependencies {
    implementation project(':sbp-spring-boot-starter')
    implementation project(':demo-api')
    implementation project(':sbp-spring-boot-jpa-starter')

    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-data-jpa"
    implementation 'org.laxture:spring-static-ctx:0.1.2'

    runtimeOnly "org.postgresql:postgresql"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    if (isSpringBoot4) {
        testImplementation "org.springframework.boot:spring-boot-webmvc-test"
        testImplementation "com.fasterxml.jackson.core:jackson-databind"
    }
}

//*************************************************************************
// App Properties
//*************************************************************************

mainClassName = 'demo.sbp.app.DemoJpaApp'

manifest {
    attributes 'Main-Class': 'demo.sbp.app.DemoJpaApp'
}