def isSpringBoot4 = VersionNumber.parse("${springBootVersion}").getMajor() >= 4

configurations.testImplementation {
    exclude group: 'org.springframework.boot', module: 'spring-boot-starter-web'
    exclude group: 'org.springframework', module: 'spring-webmvc'
}

sourceSets {
    test {
        java {
            srcDir isSpringBoot4 ? 'src/test/java4' : 'src/test/java3'
        }
    }
}

dependencies {
    implementation project(':sbp-spring-boot-starter')
    implementation project(':sbp-spring-boot-springdoc-starter')

    implementation "org.springframework.boot:spring-boot-starter-webflux"
    implementation "org.springframework.boot:${aopStarter}"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    if (isSpringBoot4) {
        testImplementation "org.springframework.boot:spring-boot-webtestclient"
    }
}

//*************************************************************************
// App Properties
//*************************************************************************

mainClassName = 'demo.sbp.app.DemoAppWebFlux'

manifest {
    attributes 'Main-Class': 'demo.sbp.app.DemoAppWebFlux'
}